version: 2
jobs:
  pr_checks:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: "Build" 
          command: node restapi.js
      - run: 
          name: "Test"
          command: |
            npx jest
            echo 'Done'
  build:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: "Build" 
          command: node restapi.js
      - run: 
          name: "Test"
          command: |
            npx jest
            echo 'Done'

workflows:
  version: 2
  pr_check_workflow:
    jobs:
      - pr_checks
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
